//Tab1
export const PETS_HOME = 'PETS_HOME';
export const PETS_DETAILS = 'PETS_DETAILS';
//Tab2
export const MARINE_HOME = 'MARINE_HOME';
export const MARINE_DETAILS = 'MARINE_DETAILS';
//Tab3
export const LANDSCAPES_HOME = 'LANDSCAPES_HOME';
export const LANDSCAPES_DETAILS = 'LANDSCAPES_DETAILS';
//Tab4
export const FLORAL_HOME = 'FLORAL_HOME';
export const FLORAL_DETAILS = 'FLORAL_DETAILS';
//Tab5
export const ANIMALS_HOME = 'ANIMALS_HOME';
export const ANIMALS_DETAILS = 'ANIMALS_DETAILS';
